name: Development
run-name: Compilation & Quality Checks
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '*'
      - '!develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Build
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          option: '--no-build-cache'
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit Tests
        run: |
          ./gradlew test